package com.lior.application.rh_test.util.exceptions;

public class UserNotFoundException extends RuntimeException{
    
}
